name: Links

on:
  pull_request:
    branches:
      - master

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false
          args: "--config ./ci/lychee.toml"
          output: ./lychee/out.md

      - name: Save lychee cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .lycheecache
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}

      - name: Post Comment on Pull Request
        if: github.event_name == 'pull_request' && steps.lychee.outputs.exit_code != 0
        run: |
          echo "The link checker found some issues. Please review the report below:" > comment.md
          echo "" >> comment.md
          cat ./lychee/out.md >> comment.md
          gh pr comment ${{ github.event.pull_request.number }} --body-file comment.md

      - name: Fail Workflow
        if: github.event_name == 'pull_request' && steps.lychee.outputs.exit_code != 0
        run: exit 1
