name: Links

on:
  pull_request:
    branches:
      - master

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false
          # Use a custom GitHub token to avoid rate limit issues
          # token: ${{ secrets.CUSTOM_TOKEN }}

      - name: Post Comment on Pull Request
        if: github.event_name == 'pull_request' && steps.lychee.outputs.exit_code != 0
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Link Checker Report
          message: |
            The link checker found some issues. Please review the report below:
            ```
            ${{ steps.lychee.outputs.report }}
            ```
