name: Test Rust Project

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: 'true'
          toolchain: nightly

      - name: Run tests
        run: |
          cargo +nightly test  -- -Z unstable-options --format json --report-time | tee results.json

      - name: Prepare junit report
        id: cargo_reporter
        uses: innoq/action-cargo-test-report@v1
        with:
          cargo-test-report-json: 'results.json'

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@main
        if: always()
        with:
          check_name: Test Report
          fail_on_failure: true
          require_tests: true
          summary: ${{ steps.cargo_reporter.outputs.summary }}