name: Test Rust Project

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: 'true'
          toolchain: nightly

      - name: Run tests
        run: |
          cargo +nightly test  -- -Z unstable-options --format junit --report-time | tee results.xml 

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5.2.0
        if: always()
        with:
          check_name: Test Report
          fail_on_failure: true
          require_tests: true
          report_paths: '**/results.xml'