name: Spell Check

on:
  pull_request:
    paths:
      - "src/**"

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Aspell
        run: sudo apt-get update && sudo apt-get install -y aspell aspell-en

      - name: Prepare Dictionary
        run: |
          if [ ! -f ./ci/dictionary.txt ]; then
              echo "Generating dictionary file as it doesn't exist."
              echo "personal_ws-1.1 en 0 utf-8" > ./ci/dictionary.txt
              find ./src -type f -name '*.md' -exec cat {} + | aspell --ignore 3 list | sort -u >> ./ci/dictionary.txt
          fi

      - name: Run Spell Check
        run: |
          dict_path="./ci/dictionary.txt"
          retval=0

          for fname in $(find ./src -type f -name '*.md'); do
              errors=$(aspell --ignore 3 --personal="$dict_path" list < "$fname")
              if [ -n "$errors" ]; then
                  echo "Typos found in $fname:"
                  echo "$errors" | tr ' ' '\n'
                  retval=1
              fi
          done

          exit $retval

      - name: Fail on Typos
        if: failure()
        run: |
          echo "::error title=Spell Check::Typos were detected. Please fix the reported issues."

      - name: Report Success
        if: success()
        run: echo "No typos found!"

